### ISSUE TITLE
Do not dismiss failures prior to serialization

### ISSUE THREAD

**Issue by BenFradet** [snowplow/kinesis-s3#101]

**Comment by alexanderdean** [comment]
Thanks @BenFradet. Do we have a sense yet of what kinds of scenarios could lead to events failing pre-serialization?

**Comment by BenFradet** [comment]
Haven't looked into that yet but when inspecting the logs I noticed a few times that groups of messages seem to reach this https://github.com/snowplow/kinesis-s3/blob/master/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/s3/S3Emitter.scala#L121 but are never heard of again that's what made me look into this in the first place.
