### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ranvijayj** [snowplow/kinesis-s3#112]
![screen shot 2017-08-14 at 4 25 07 pm](https://user-images.githubusercontent.com/10911504/29269070-4d648eb6-810d-11e7-891f-a136278b3de4.png)

**Comment by BenFradet** [comment]
As indicated in the stack trace, there is an issue with your configuration.

**Comment by ranvijayj** [comment]
I resolved that. Closing...

Got another issue now.. Posting.
