### ISSUE TITLE
Add message when requiring that the Kinesis stream exist fails

### ISSUE THREAD

**Issue by ranvijayj** [snowplow/kinesis-s3#113]
![screen shot 2017-08-14 at 4 49 31 pm](https://user-images.githubusercontent.com/10911504/29269738-c139c56a-8110-11e7-8d8d-44e9d592cded.png)

**Comment by ranvijayj** [comment]
![screen shot 2017-08-14 at 4 51 37 pm](https://user-images.githubusercontent.com/10911504/29269763-e1351f36-8110-11e7-8910-a4f591978f9c.png)

**Comment by BenFradet** [comment]
This is because the kinesis stream you specified in the configuration doesn't exist.

**Comment by ranvijayj** [comment]
THis got working, yeah but there was no proper output.
BUt data not going to S3. Can you help me what I should be putting here:

![screen shot 2017-08-16 at 12 38 07 pm](https://user-images.githubusercontent.com/10911504/29351364-0aba8402-8280-11e7-86fe-7a3e7678c360.png)



Another problem is that the out stream is a compulsory parameter? Will need an extra kinesis stream running too?

**Comment by ranvijayj** [comment]
Added endpoint: "https://s3.ap-south-1.amazonaws.com" as well.

It does still run but nothing displays on the screen and nothing going to S3 while events being generated on Kinesis. 
![screen shot 2017-08-16 at 12 46 00 pm](https://user-images.githubusercontent.com/10911504/29351624-20ff32c0-8281-11e7-8f6e-040ea9bf68fd.png)

**Comment by ranvijayj** [comment]
Tried via sbt as well
![screen shot 2017-08-16 at 12 51 21 pm](https://user-images.githubusercontent.com/10911504/29351756-b7882eea-8281-11e7-924e-535b4b7f4bf9.png)


Please help.

**Comment by aldemirenes** [comment]
Please direct any support questions to our forums: https://discourse.snowplowanalytics.com/
