### ISSUE TITLE
Initialize bad stream eagerly rather than lazily

### ISSUE THREAD

**Issue by fblundun** [snowplow/kinesis-s3#18]
https://github.com/snowplow/kinesis-s3/blob/master/src/main/scala/com.snowplowanalytics.snowplow.storage.kinesis/s3/sinks/KinesisSink.scala#L77

Originally this was so that the app wouldn't create the bad stream until it became necessary. But now that we have https://github.com/snowplow/snowplow/issues/1529, the lazy val just means that if the stream doesn't exist, that error won't be caught immediately.

**Comment by alexanderdean** [comment]
Makes sense!
