### ISSUE TITLE
Unify logger configuration

### ISSUE THREAD

**Issue by fblundun** [snowplow/kinesis-s3#19]
See #1367

The point of this is that it will be possible to configure the log level for both kinesis-s3 and the KCL by starting the application like this:

```
java -jar -Dorg.slf4j.simpleLogger.defaultLogLevel=debug kinesis-lzo-sink-0.x.0 --config myhocon
```

**Comment by alexanderdean** [comment]
Can we move the log level config into the hocon?

**Comment by fblundun** [comment]
Looks like you can configure it by changing the system property from inside the app:

```scala
val logLevel = config.getString("logLevel")
System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, logLevel)
```

(from http://stackoverflow.com/questions/14544991/how-to-configure-slf4j-simple)
