### ISSUE TITLE
Rename binary to snowplow-kinesis-s3

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/kinesis-s3#27]
From snowplow-lzo-s3-sink

**Comment by jbeemster** [comment]
https://github.com/snowplow/kinesis-s3/search?utf8=%E2%9C%93&q=snowplow-lzo-s3-sink

I found three instances of this, do we want them all changed to snowplow-kinesis-s3?

**Comment by alexanderdean** [comment]
Yes please!
