### ISSUE TITLE
Reduce assembly time by disabling assemblyCacheOutput

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/kinesis-s3#4]

**Comment by alexanderdean** [comment]
Migrated from: https://github.com/snowplow/snowplow/issues/1668

**Comment by fblundun** [comment]
@jbeemster have you tested whether this worked? It was still really slow when I did this for the Scala Stream Collector (https://github.com/snowplow/snowplow/issues/1665)

**Comment by jbeemster** [comment]
@fblundun no I did not get a chance to test it as of yet.  I just pulled it from the assembly.  I was thinking that your idea of beefing out our VMs might be the smarter route to solving the slow build issues.

**Comment by jbeemster** [comment]
Woops did not see your update!  So we need to start building in host instead of guest?

**Comment by fblundun** [comment]
Sounds like the current plan is to get a build server, and meanwhile hope that the author of sbt-assembly works out what's causing the problem...
