### ISSUE TITLE
Prevent empty files from being written to S3

### ISSUE THREAD

**Issue by christoph-buente** [snowplow/kinesis-s3#47]
If there are no events happening and the buffer timeout hits an empty file is written to S3. I fact there are two files:
* 8 Byte lzo.index file
* 555 Byte empty lzo file

Usually this does not happen in production, but in staging environment.

![bildschirmfoto 2015-09-14 um 10 58 00](https://cloud.githubusercontent.com/assets/36998/9846000/89d78c06-5acf-11e5-92b6-7b0ac08da40c.png)

**Comment by alexanderdean** [comment]
Good catch! Thanks for raising

**Comment by christoph-buente** [comment]
Actually the 555 Byte events we see are not empty, but somehow broken. See the umcompressed thrift event.

    )ÿ’XÕL)≤ºWô!qΩˇ÷byte[]…d
    60.213.133.83
    »O»Û0~“UTF-8‹ssc-0.5.0-kinesis,&Mozilla/3.0 (compatible; Indy Library)@
    /manager/htmlJ^Authorization: Basic Og==2User-Agent: Mozilla/3.0 (compatible; Indy Library)Accept: text/html, */*Host: 54.72.99.4:8080Content-Type: text/htmlh	text/htmlê
    54.72.99.4ö$daafc6a4-476a-4b26-8255-c966076e39fbziAiglu:com.snowplowanalytics.snowplow/CollectorPayload/thrift/1-0-0

**Comment by fblundun** [comment]
@christoph-buente - the events go through 2 transformations before ending up in S3: first the Scala Stream Collector serializes them as Thrift objects (using [this schema](https://github.com/snowplow/snowplow/blob/master/2-collectors/thrift-schemas/collector-payload-1/src/main/thrift/collector-payload.thrift)), then this project lzo compresses them. Have you undone the lzo compression without undoing the Thrift serialization? That can lead to outputs containing weird characters.

**Comment by christoph-buente** [comment]
Yes, i just uncompressed the file using ```lzop -d``` 

I know the binary characters are from thrift, but also the event is missing the full url and so many other information, it is basically crap. But in the first place i thought it was an actual 0byte file compressed with lzo creating this 555b overhead.

**Comment by alexanderdean** [comment]
I can see the `/manager/html` string in there - this is a common sign that a malicious bot is trying to penetrate your collector as a PHP webserver. So it's a valid raw payload (if not a valid event).
