### ISSUE TITLE
Clarify comment

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/kinesis-s3#56]
This comment is rather vague. Please specify the mechanism being used to determine "first". E.g. to have the notion of "first", there must be some atomic operation going on somewhere. Presumably a file is written somewhere, or there is some Amazon API being used for this. 

I have no doubt that I can read the source code to figure it out, but this is about usability, and I suspect to some extent documentation of desired behaviour. 

``` 
# Note: This only affects the first run of this application
      # on a stream.
```

**Comment by jbeemster** [comment]
On the first run of the application the Kinesis Connectors Library creates a DynamoDB table to keep track of what it has consumed from the stream so far.  Either on first run it starts consuming from LATEST being the most recent record in the stream or TRIM_HORIZON being the oldest record available in the stream.

For more information on the various fields in the config file please consult the technical documentation here: https://github.com/snowplow/snowplow/wiki/kinesis-lzo-s3-sink-setup#configuration

Hope that helps!

**Comment by 0xABAB** [comment]
It does. If you could just copy paste that into that file (and/or put it in the documentation for the Scala collector), then you can close this minor ticket again. 

Thanks for the quick reply.

**Comment by 0xABAB** [comment]
Can you explain what is supposed to happen if I pull the plug from this server and restart it again? Will I end up with partially duplicated data on S3?

**Comment by jbeemster** [comment]
The DynamoDB table is updated every time that events are successfully sent to S3.  So if you managed to shut the server down just after sending and just before it was able to update DynamoDB (a very small amount of time) you might end up with a small amount of duplication when it is restarted.

This mean that all events are sent `at-least-once` and ensures that no data is lost.

I hope that clarifies things for you and in future could you please ask these questions on the user forum!

**Comment by ezefranca** [comment]
https://github.com/contact?report=0xABAB

**Comment by rscircus** [comment]
@ezefranca, no abuse here. @0xABAB is earning some HN fame, as s/he seems to be rather outspoken considering BigCorp open sourcing software for profit. Sorry for polluting that issue, snowplow.
