### ISSUE TITLE
Pipelined requests

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/kinesis-s3#62]
When synchronizing to a substantial amount of Kinesis data, I notice that my network is used for a few seconds, then it stops, and this repeats. An efficient program would continuously saturate the network. 

To fix this, you essentially need to add multiple concurrent requests to the program.

**Comment by alexanderdean** [comment]
You can't reason about how Kinesis S3 interacts with the AWS Kinesis API by looking at network traffic - that's far too low level, you're missing multiple logical layers in-between which dictate behavior. Closing this ticket - if you have a cogent suggestion for improving efficiency, a PR is welcome!

**Comment by 0xABAB** [comment]
OK, after some further analysis, it seems that the reason it's so slow is that Kinesis itself is a rather low-performance service itself (per shard). 

The network could be saturated by doing multiple concurrent calls `GetRecords` with  `GetShardIterator` initialized with suitable `AT_SEQUENCE_NUMBER`s, if there would be no other Amazon limitations. 

See: http://docs.aws.amazon.com/streams/latest/dev/service-sizes-and-limits.html

So, within the rather low limits of Amazon, this program works fine. 

As such, this issue can now be closed, but the less specific issue that syncing to a fairly high volume data stream is slow, is still somewhat of an issue. I suppose it should be possible to temporarily raise the number of shards, but that's more of a simple idea than a well considered plan.

**Comment by alexanderdean** [comment]
Hi @0xABAB - you are right, there are some specific limitations around accessing Kinesis which govern this application's performance.

> the less specific issue that syncing to a fairly high volume data stream is slow, is still somewhat of an issue

With distributed commit logs like Kinesis/Kafka, you typically have a single worker aka thread processing each shard/partition. In this environment, the relevant definition of slow is "a single thread cannot keep up with (i.e. lag steadily increases) a maximally utilized shard".

In this case, you have to either allocate more shards than the throughout requires (to increase the number of workers that can service the stream) and/or bump the server spec (so each worker can do more).

But Kinesis S3 running on a fairly middling server can comfortably keep up with a maximally utilized Kinesis shard, so within the constraints of Kinesis it is not slow.
