### ISSUE TITLE
Can't see any data sinked into S3.

### ISSUE THREAD

**Issue by shailesh17mar** [snowplow/kinesis-s3#68]
I have deployed kinesis -s3-sink. After deploying it on ec2 instance it runs successfully and logs repeatedly "Successfully published X datums". But, I dont see any data in my S3 bucket. Is there something I am missing? If not, the sinking process is realtime or does it takes a lot of time for initial setup.

**Comment by jbeemster** [comment]
Hi @shailesh17mar could you please post your question as a new topic on our [Discourse forum](http://discourse.snowplowanalytics.com/).
