### ISSUE TITLE
kinesisSinkEndpoint is of different format in Beijing

### ISSUE THREAD

**Issue by Jimexist** [snowplow/kinesis-s3#70]
i.e. it is `kinesis.cn-north-1.amazonaws.com.cn`

**Comment by alexanderdean** [comment]
Oh! Good point...

**Comment by bobshaw1912** [comment]
I made a pull request for kinesis-s3. Could you please take a look for potential merge?

**Comment by alexanderdean** [comment]
The PR is here: https://github.com/snowplow/kinesis-s3/pull/71

**Comment by BenFradet** [comment]
closing since this will be part of #71
