### ISSUE TITLE
Add support for new AWS regions

### ISSUE THREAD

**Issue by jbeemster** [snowplow/kinesis-s3#75]

**Comment by BenFradet** [comment]
@jbeemster do you have any insights into what this would entail?

**Comment by jbeemster** [comment]
Hey @BenFradet - this entails:

1. Updating all AWS libraries to the latest versions
2. Deploying this in one of the new regions to check interop with Kinesis & S3

**Comment by BenFradet** [comment]
ok will check once I do some integration testing

**Comment by BenFradet** [comment]
tested in the tokyo region :+1: , closing and descheduling.
